### ISSUE TITLE
I am adding dropdown after_email but it is not working but when i add it after_billing_fields it work

### ISSUE THREAD

**Issue by RabbiaFayaz** [strangerstudios/pmpro-state-dropdowns#15]
$dropdown = new PMProRH_Field("gender", "select", array("options"=>array("" => "", "male"=>"Male", "female"=>"Female")));
	pmprorh_add_registration_field("after_email", $dropdown);

**Comment by andrewlimaza** [comment]
Hi @RabbiaFayaz 

This seems to be a Paid Memberships Pro related issue and not a PMPro State Dropdown issue.

However, I've encountered this issue previously and to solve this issue, when adding to after_email, please add `"profile" => true,` to your field code and this should solve your issue.

**Comment by andrewlimaza** [comment]
Closing this issue as it's not relating to PMPro State Dropdown add on.
