### ISSUE TITLE
State Dropdown not working on Update Billing page.

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-state-dropdowns#28]
The dropdown function does not work on the update billing page.

Steps to recreate:
- Install/Activate the states dropdown add on
- Create a new user, select state during checkout
- Try updating the User's details on the Billing Page.

Related Ticket: https://www.paidmembershipspro.com/forums/topic/paid-memberships-pro-state-dropdowns-add-on-not-working/

**Comment by andrewlimaza** [comment]
Fixed this in latest release.
