### ISSUE TITLE
Shipping country is not updated correctly

### ISSUE THREAD

**Issue by jwonder** [strangerstudios/pmpro-state-dropdowns#30]
I added it on the code in the same way that billing address is done.  See attached update.

[pmpro-state-dropdowns.php.zip](https://github.com/strangerstudios/pmpro-state-dropdowns/files/4808704/pmpro-state-dropdowns.php.zip)

**Comment by jwonder** [comment]
I also added:

        jQuery("[name='pmpro_scountry']").attr('id', 'scountry');
        jQuery("[name='pmpro_sstate']").attr('id', 'sstate');

to the countries-main.js file under their bcountry counterparts!

**Comment by andrewlimaza** [comment]
I've tried to replicate this but I am unable to do so @jwonder. I am going to mark this ticket as closed, if you still run into issues with this please can you open a support ticket at www.paidmembershipspro.com and we'll debug this further.
