### ISSUE TITLE
Enhancement: states from php

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/pmpro-state-dropdowns#34]
I think it would be better to use a PHP generated array to define the states. Maybe shared with [another well-known plugin](https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php).

Benefits:
1. i18n
2. filterable
3. validate and convert 2-letter codes to state name in php scripts (es. invoice/e-invoice generation)

**Comment by andrewlimaza** [comment]
I like this idea, we'll look into this further.

**Comment by andrewlimaza** [comment]
This is now completed with the latest stable version.
