### ISSUE TITLE
Use pmpro_is_checkout()

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-state-dropdowns#40]
Right now, the `enqueue_styles_scripts()` function checks whether the user is on the checkout page by using `! is_page( $pmpro_pages['checkout'] )`, which only checks for the checkout page set in PMPro settings. Link to line: https://github.com/strangerstudios/pmpro-state-dropdowns/blob/16d84a22e717108ecd34ebcc84c91af5baec6e3d/pmpro-state-dropdowns.php#L66

We should instead use `pmpro_is_checkout()` as that function is filterable, which helps in the case that the user has multiple checkout pages. Here's a link to that function in core PMPro: https://github.com/strangerstudios/paid-memberships-pro/blob/84cd830e00ff3a4543078449c98b62917757b6de/includes/functions.php#L3175-L3213

Would be especially helpful for WPML, which creates a page for each language.

**Comment by andrewlimaza** [comment]
This does fix the issue of loading the scripts, but the values inside the JavaScript for the values aren't translatable. This would also need a bit more work.

**Comment by andrewlimaza** [comment]
This fix is pretty easy the 'pmpro_is_checkout' fixes this. The translation issue is a bigger issue altogether.

**Comment by andrewlimaza** [comment]
This is completed with latest commit.
