### ISSUE TITLE
State Dropdown Add-On Not Working

### ISSUE THREAD

**Issue by Zabriskie42** [strangerstudios/pmpro-state-dropdowns#42]
I just obtained a website that was built by another developer. He had PMP installed with the premium add-ons installed, but no api key. 

The state dropdown menu stopped showing the contents of the list to choose the state you live in, leaving it impossible to renew or create new memberships. 

I read on here that that was a bug in version .1, which I have since obtained an API key, updated PMP and the add-on, and wordpress all to the latest versions. Cleared the cache. 

But the dropdown is still not showing the list of states. 

Please advise. Thank you

**Comment by Zabriskie42** [comment]
Now when I open the website in an incognito window the dropdown shows up.

**Comment by andrewlimaza** [comment]
Are you still having this issue @Zabriskie42, can you tell me what page you are having this issue was it only on the checkout page?

If so, please can you exclude caching for your checkout page as incognito usually serves an uncached version and seems to be cache related.

**Comment by andrewlimaza** [comment]
For support relating this, please reach out to www.paidmembershipspro.com/support

Our team will assist you further.
