### ISSUE TITLE
Codes for Singapore need updating.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-state-dropdowns#43]
The plugin adds regions,12,3,4,5 to Singapore.  Would be helpful to update to be clearer.
"Singapore","SG","Central Singapore~01|North East~02|North West~03|South East~04|South West~05"
(The 0 is removed in the database).  Can we add the SG- in front?

Wikipedia lists them like this:

SG-01 | Central Singapore
SG-02 | North East
SG-03 | North West
SG-04 | South East
SG-05 | South West

**Comment by andrewlimaza** [comment]
This has been resolved in latest commit.
