### ISSUE TITLE
State dropdown update issue

### ISSUE THREAD

**Issue by rjliss** [strangerstudios/pmpro-state-dropdowns#44]
Update failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

**Comment by andrewlimaza** [comment]
Hi @rjliss 

Are you still having this issue? This sounds like the .zip file was incorrect when trying to download and install it to WordPress (during the update process).

**Comment by andrewlimaza** [comment]
Updating this error, this could be due to an incorrect license key when downloading/updating the plugin through the dashboard.
