### ISSUE TITLE
Conflict with Shipping Add On and pmpro_default_country variable

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-state-dropdowns#45]
When a site has the **[Shipping Add On](https://www.paidmembershipspro.com/add-ons/shipping-address-membership-checkout/)** installed and active and **State Dropdown Add On**, the pmpro_default_country variable is no longer recognized.

![default-country](https://user-images.githubusercontent.com/8083630/120514954-cfe26500-c39b-11eb-9922-813b49be22ba.png)

**Comment by andrewlimaza** [comment]
This has been resolved with the latest commit - https://github.com/strangerstudios/pmpro-state-dropdowns/commit/6ed2b7ce417f965c7660c6c5aa460355c60d9838
