### ISSUE TITLE
Update Great Britain to United Kingdom

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-state-dropdowns#48]
**Feature request**
Update Great Britain to [United](https://en.wikipedia.org/wiki/United_Kingdom) [Kingdom](https://www.britannica.com/story/whats-the-difference-between-great-britain-and-the-united-kingdom).

This came up in ticket 462140.

> See the examples here: http://country-regions.github.io/country-region-selector/. The country dropdown values are by default the same as the display values (the full country names). By adding the `data-value=“shortcode”` attribute to the country field, the values will be a 2-char character code. See Example 8 for a similar example with the region dropdown. And then in our code we add that shortcode parameter in our JavaScript: https://github.com/strangerstudios/pmpro-state-dropdowns/blob/master/js/countries-main.js#L10 (e.g. `jQuery('#bstate').attr('data-value', 'shortcode');`). 

**WordPress Environment**
<details> 
Paid Memberships Pro 2.9.7, State Dropdowns Add On 0.3, WordPress 6.1.1, PHP 8.0.26 
</details>

**Comment by andrewlimaza** [comment]
This has been resolved with the latest version. We use the default PMPro countries now and United Kingdom shows as a country option - please update to version 0.4
