### ISSUE TITLE
Language template missing / Partially configured bundle errors in Loco Translate

### ISSUE THREAD

**Issue by dugost** [strangerstudios/pmpro-state-dropdowns#52]
In Overview, this message appears:

> This bundle isn't fully configured, so we don't know what the following files are for. Click the [setup] tab to complete the bundle configuration.

In Setup:

> Partially configured bundle
> This bundle's configuration has been automatically detected, but isn't fully complete.
> 2 files can't be matched to a known set of strings

In New Language:

> Template missing
> This bundle's template file doesn't exist yet. We recommend you create it before adding languages.

**Comment by mircobabini** [comment]
PR is ready #41

**Comment by andrewlimaza** [comment]
@dugost V0.4 has gone out with improved localization. This should be resolved now. Please don't hesitate to reach out if you still experiencing issues with this.
