### ISSUE TITLE
When "State" does not have dropdown options (e.g., UK, Croatia, Poland) the 3D Authentication fails with the message "Please complete all required fields."

### ISSUE THREAD

**Issue by nookale** [strangerstudios/pmpro-state-dropdowns#57]
**Describe the bug**
When "State" does not have a dropdown menu (e.g., UK, Croatia, Poland), the 3D Authentication fails with the message "Please complete all required fields," highlighting the State field.

**To Reproduce**
- Create a stage environment
- Switch Stripe from Live/Production to Sandbox/Testing
- Checkout Membership. Use Stripe test cards for 3D Secure Authentication (https://stripe.com/docs/testing?testing-method=card-numbers#regulatory-cards). Use card 4000002760003184
- Try several times. The Countries where the State Dropdown is auto-populated (e.g., USA, Spain) work fine. The Countries where there is not dropdown (e.g., UK, Croatia, Poland)  fail after authentication with the bank.

In a production environment, even if the checkout fails, the user gets an account in Wordpress without membership level, and Stripe records the following: <<3D Secure authentication succeeded
This transaction has been authenticated with 3D Secure 2. The customer was authenticated via a [challenge](https://stripe.com/guides/3d-secure-2#frictionless-authentication) flow, and shown a challenge window from their bank.>> However, the transaction is marked as incomplete, and initially, it says that an action is required on the part of the Stripe account owner. Finally, it fails, but the status of the transaction does not change: incomplete.

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by andrewlimaza** [comment]
@nookale I tried this with sandbox account and used the card to test the 3D Secure. I authenticate the 3D Secure from Stripe's sandbox popup and it goes through without any issues.

I chose a country that did not autopopulate the dropdown and kept it as a text field, entered a value and completed checkout.

Can you confirm for me if you're still running into this issue? If so, a workaround would be to use Stripe Checkout (https://www.paidmembershipspro.com/gateway/stripe/stripe-checkout/)

This should resolve the issue if it still continues to happen for you. 

I'm not going to close this issue unless you confirm it's been resolved. Please be sure to use the latest Paid Memberships Pro version.

**Comment by nookale** [comment]
@andrewlimaza I checked with the latest Paid Memberships Pro, and all seems to be working correctly.

Thanks.
