### ISSUE TITLE
Kosovo not recognised as separate international country yet

### ISSUE THREAD

**Issue by Jimbojetset2** [strangerstudios/pmpro-state-dropdowns#58]
We are long term users of PM Pro and think it is absolutely perfect for our needs especially with the extra plugins modules just have one small bugbear with the pmpro-state-dropdowns plugin.
We have a few customers who are unhappy that Kosovo is not in the list of countries in the as a separate independent country. It is causing a bit of offence to some customers many of whom are political/social academics. Can it be added anytime soon please?
From wikipedia; "Among the G20 countries, eleven (including all seven G7 countries) have recognised Kosovo as an independent state: Australia, Canada, France, Germany, Italy, Japan, Saudi Arabia, South Korea, Turkey, the United Kingdom, and the United States."
Many thanks for all your hard work

**Comment by andrewlimaza** [comment]
@Jimbojetset2 I removed it from the states dropdown so you may add it as a country using the filter mentioned above. It looks like the alpha-2 code is "XK" for the time being.
